name: odoo-dev
services:
  odoo:
    image: odoo:17
    container_name: odoo-container
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  odoo:
  postgres: