name: odoo-dev
services:
  odoo:
    image: odoo:latest
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - TZ=Asia/Kolkata
    volumes:
      - odoo:/var/lib/odoo
      - ./addons:/mnt/extra-addons

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - TZ=Asia/Kolkata
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  odoo:
  postgres: